"""Localized labels for entities preloaded into SQLite ledgers."""

from app.domain.registry.model.user_preferences import Language


CATEGORY_LABELS: dict[Language, dict[str, str]] = {
    "pt-BR": {
        "food": "Comida",
        "groceries": "Mercado",
        "restaurants": "Restaurantes",
        "snacks": "Cafés e lanches",
        "housing": "Moradia",
        "rent": "Aluguel e condomínio",
        "household_bills": "Contas da casa",
        "electricity": "Energia elétrica",
        "water": "Água",
        "gas": "Gás",
        "internet": "Internet e celular",
        "decoration": "Decoração",
        "transport": "Transporte",
        "rides": "Aplicativos e táxi",
        "fuel": "Combustível",
        "public_transport": "Transporte público",
        "health": "Saúde",
        "pharmacy": "Farmácia",
        "therapy": "Terapia",
        "appointments": "Consultas e exames",
        "education": "Educação",
        "books": "Livros",
        "courses": "Cursos",
        "leisure": "Lazer",
        "games": "Jogos",
        "events": "Eventos",
        "cinema": "Cinema",
        "travel": "Viagens",
        "subscriptions": "Assinaturas",
        "streaming": "Streaming",
        "digital_services": "Serviços digitais",
        "electronics": "Eletrônicos",
        "peripherals": "Periféricos",
        "hardware": "Hardware",
        "tools": "Ferramentas",
        "gifts": "Presentes",
        "special_dates": "Datas especiais",
        "casual_gift": "Presente casual",
        "services": "Serviços",
        "maintenance": "Manutenção e reparos",
        "personal_care": "Cuidados pessoais",
        "loans": "Empréstimos",
        "clothing": "Roupas",
        "taxes": "Impostos",
        "income_tax": "Imposto de renda",
        "income": "Receitas",
        "salary": "Salário",
        "allowance": "Mesada",
        "scholarship": "Bolsa",
        "transfers": "Transferências",
        "investments": "Investimentos",
        "donation": "Doação",
        "one_off_donation": "Doação pontual",
        "recurring_donation": "Doação recorrente",
    },
    "en": {
        "food": "Food",
        "groceries": "Groceries",
        "restaurants": "Restaurants",
        "snacks": "Coffee and snacks",
        "housing": "Housing",
        "rent": "Rent and condominium",
        "household_bills": "Household bills",
        "electricity": "Electricity",
        "water": "Water",
        "gas": "Gas",
        "internet": "Internet and phone",
        "decoration": "Decoration",
        "transport": "Transport",
        "rides": "Rides and taxis",
        "fuel": "Fuel",
        "public_transport": "Public transport",
        "health": "Health",
        "pharmacy": "Pharmacy",
        "therapy": "Therapy",
        "appointments": "Appointments and tests",
        "education": "Education",
        "books": "Books",
        "courses": "Courses",
        "leisure": "Leisure",
        "games": "Games",
        "events": "Events",
        "cinema": "Cinema",
        "travel": "Travel",
        "subscriptions": "Subscriptions",
        "streaming": "Streaming",
        "digital_services": "Digital services",
        "electronics": "Electronics",
        "peripherals": "Peripherals",
        "hardware": "Hardware",
        "tools": "Tools",
        "gifts": "Gifts",
        "special_dates": "Special dates",
        "casual_gift": "Casual gift",
        "services": "Services",
        "maintenance": "Maintenance and repairs",
        "personal_care": "Personal care",
        "loans": "Loans",
        "clothing": "Clothing",
        "taxes": "Taxes",
        "income_tax": "Income tax",
        "income": "Income",
        "salary": "Salary",
        "allowance": "Allowance",
        "scholarship": "Scholarship",
        "transfers": "Transfers",
        "investments": "Investments",
        "donation": "Donation",
        "one_off_donation": "One-off donation",
        "recurring_donation": "Recurring donation",
    },
}

CURRENCY_LABELS: dict[Language, dict[str, str]] = {
    "pt-BR": {
        "brl": "Real",
        "usd": "Dólar americano",
        "eur": "Euro",
        "btc": "Bitcoin",
        "jpy": "Iene japonês",
        "gbp": "Libra esterlina",
    },
    "en": {
        "brl": "Brazilian real",
        "usd": "US dollar",
        "eur": "Euro",
        "btc": "Bitcoin",
        "jpy": "Japanese yen",
        "gbp": "Pound sterling",
    },
}
