FROM node:24-alpine AS frontend-build

WORKDIR /app/frontend

COPY frontend/package.json ./

RUN npm install

COPY frontend ./

RUN npm run build:production


FROM python:3.14-slim-trixie

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV REGISTRY_SCHEMA_PATH=/app/backend/app/infrastructure/persistence/sqlite/registry/schema/registry_schema.sql
ENV LEDGER_SCHEMA_PATH=/app/backend/app/infrastructure/persistence/sqlite/ledger/schema/ledger_schema.sql
ENV REGISTRY_DB_PATH=/data/registry/registry.sqlite
ENV LEDGER_DBS_DIR=/data/ledgers

WORKDIR /app

COPY backend/app/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY backend /app/backend
COPY --chmod=755 backend/bin/moedeiro /usr/local/bin/moedeiro
COPY --from=frontend-build /app/frontend/dist/moedeiro-web/browser /app/frontend

ENV PYTHONPATH=/app/backend
ENV FRONTEND_DIST_PATH=/app/frontend

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
